<a href="https://colab.research.google.com/github/jasonstoy/pytorch_practice/blob/master/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTORCH**

- May 21, **2020**

In [0]:
import torch
import numpy as np

In [3]:
x = torch.empty(5,3)
x

tensor([[2.5004e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
x = torch.ones(5,3,dtype= torch.long)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [9]:
y = torch.empty(5,3).long()
y

tensor([[                   0,                    0,                    0],
        [                   0,                    0,                    0],
        [                   0,                    0,                    0],
        [                   0,                    0, -9223372036854775808],
        [-9223372036854775808, -9223372036854775808,                    0]])

In [0]:
z = x + y
# inplace 
# z.add_(x) 

In [17]:
x = torch.randn(4,4)
x

tensor([[ 1.8231, -1.8301,  0.0731,  0.0339],
        [-1.1226, -1.2939,  0.8188, -0.6041],
        [ 0.7105, -1.5135,  0.0739,  0.1089],
        [-1.6870,  0.8656,  1.2959, -0.3530]])

In [19]:
# reshape
x.view(2,8)

tensor([[ 1.8231, -1.8301,  0.0731,  0.0339, -1.1226, -1.2939,  0.8188, -0.6041],
        [ 0.7105, -1.5135,  0.0739,  0.1089, -1.6870,  0.8656,  1.2959, -0.3530]])

In [20]:
x.view(-1,8)

tensor([[ 1.8231, -1.8301,  0.0731,  0.0339, -1.1226, -1.2939,  0.8188, -0.6041],
        [ 0.7105, -1.5135,  0.0739,  0.1089, -1.6870,  0.8656,  1.2959, -0.3530]])

In [22]:
x = torch.randn(1)
x.item()

0.7784336805343628

In [25]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [26]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [28]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [29]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [3]:
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda')

In [0]:
y = torch.ones(5).to(device)

In [7]:
y.to('cpu').numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

## 2 layer NN

In [0]:
N, D_in, H, D_out = 64, 1000, 100, 10

In [0]:
x = np.random.randn(N,D_in)
y = np.random.randn(N,D_out)

In [0]:
w_1 = np.random.randn(D_in, H)
w_2 = np.random.randn(H,D_out)

In [0]:
learning_rate = 1e-6

In [0]:
for it in range(500):
  # forward pass
  h = x.dot(w_1)
  h_relu = np.maximum(h,0)
  y_pred = h_relu.dot(w_2)

  #compute loss
  loss = np.square(y_pred-y).sum()
  print(it, loss)

  #compute gradient
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w_2 = h_relu.T.dot(grad_y_pred)
  grad_h_relu = grad_y_pred.dot(w_2.T)
  grad_h = grad_h_relu.copy() 
  grad_h[h<0] = 0
  grad_w_1 = x.T.dot(grad_h)

  #update w1 w2
  w_1 -= learning_rate * grad_w_1
  w_2 -= learning_rate * grad_w_2

 - Pytorch version

In [0]:
x = torch.randn(N,D_in)
y = torch.randn(N,D_out)

In [0]:
w_1 = torch.randn(D_in, H)
w_2 = torch.randn(H,D_out)

In [0]:
learning_rate = 1e-6

In [0]:
for it in range(500):
  # forward pass
  h = x.mm(w_1)
  h_relu = h.clamp(min=0)
  y_pred = h_relu.mm(w_2)

  #compute loss
  loss = (y_pred-y).pow(2).sum().item()
  print(it, loss)

  #compute gradient
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w_2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w_2.T)
  grad_h = grad_h_relu.clone() 
  grad_h[h<0] = 0
  grad_w_1 = x.t().mm(grad_h)

  #update w1 w2
  w_1 -= learning_rate * grad_w_1
  w_2 -= learning_rate * grad_w_2

In [0]:
x = torch.tensor(1.,requires_grad=True)
w = torch.tensor(2.,requires_grad=True)
b = torch.tensor(3.,requires_grad=True)

y = w*x + b
y.backward()

In [35]:
print(w.grad)

tensor(1.)


In [0]:
x = torch.randn(N,D_in)
y = torch.randn(N,D_out)

w_1 = torch.randn(D_in, H, requires_grad=True)
w_2 = torch.randn(H, D_out, requires_grad=True)

In [0]:
for i in range(500):
  # forward pass
  y_pred = x.mm(w_1).clamp(min=0).mm(w_2)

  #compute loss
  loss = (y_pred-y).pow(2).sum() # computation graph
  print(it, loss.item())

  #compute gradient
  w_1.grad.zero_()
  w_2.grad.zero_()
  loss.backward()

  with torch.no_grad():
    w_1 -= learning_rate * w_1.grad
    w_2 -= learning_rate * w_2.grad




In [0]:
w_1.grad
w_2.grad

## NN

In [0]:
import torch.nn as nn

In [0]:
model = nn.Sequential(
    nn.Linear(D_in,H),
    torch.nn.ReLU(),
    nn.Linear(H,D_out)
)

loss_fn = nn.MSELoss(reduction='sum')

learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

#init weight with normal
# torch.nn.init.normal_(model[0].weight)
# torch.nn.init.normal_(model[2].weight)


for i in range(500):
  # forward pass
  y_pred = model(x)

  #compute loss
  loss = loss_fn(y_pred,y)
  print(it, loss.item())

  #compute gradient
  optimizer.zero_grad()
  loss.backward()

  optimizer.step()


In [53]:
model[1]

ReLU()